language: node_js
node_js:
- 0.10.18
env:
- NODE_ENV=development
branches:
  only:
  - develop
install:
- npm install
- npm install -g grunt-cli
- bower install
script:
- echo "Running tests"
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs test/index.html
- grunt build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: U0Z5TQFhkoNmF0dtUwWwIaISubJdt/EDIcFfk2EQhAN1VSsUAznfp5zRwl8ERmNZJZ3eEvNM5vmDGQnifmiNMN3CT5Crt9cXxEq/4opTJuC8V7STyjedTbS2BmUuOIjbrJCQZsS/T1DX1ox8vSlP2jGGy4qK+PaZyW4dApo4kh4=
  app:
    develop: cottage-booking
notifications:
  email:
    recipients:
    - karl@neontribe.co.uk
    - rob@neontribe.co.uk
    on_success: always
    on_failure: always
