language: node_js
node_js:
- 0.10.18
env:
- NODE_ENV=development
branches:
  only:
  - develop
install:
- npm install
- npm install -g grunt-cli
- bower install
script:
- echo "Running tests"
- ./node_modules/mocha-phantomjs/bin/mocha-phantomjs test/index.html
- grunt build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: YWyYhMOo9Z8KFW+8GDf9Oshkt0LDroHiWLm+7L6A/l16hAdaUaPZ48RNe8YzkqqwUOi2URUthuCBhqYAFKVYZW7kSYOwyXZ/mrQrAaoEoGpjTv3vF7OoP2kH3DhfWjPEXY2ZKU3NfIFB38dSBw+7UFggDxHJ4yh6jz1l7CYH8JI=
  app:
    develop: cottage-booking
notifications:
  email:
    recipients:
    - karl@neontribe.co.uk
    - rob@neontribe.co.uk
    on_success: always
    on_failure: always
