language: node_js
node_js:
  - 0.10.18
env:
  - NODE_ENV=development
branches:
  only:
  - develop
install:
  - npm install
  - bower install
script:
  - echo "Hello Rob"
  - testee test/index.html
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: F7K/2jWlL+kvvcf3wgHk1Y8TdfQ/NWn9nId6+u6Yb2kh6X4FhWZYTeEwJLv58GQ5RCmVfxs3CgTf3Q6M6u6CbWM62/R75EJ4E5tMLI/jmQLfwcrvHVyrsm+mvrCVIA/gqmD64vtgHGh5pwAyU5RIWGEcNF4O1SLhjw8FrNagwhs=
  app:
    develop: cottage-booking